/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.paquete_de_envio;
import com.sun.awt.AWTUtilities;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.image.RescaleOp;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author alex
 */
public class cliente extends javax.swing.JFrame implements Runnable{
int x =0;
int y =0;
//Image iconoalex = Toolkit.getDefaultToolkit().getImage(getClass().getResource("\\src\\fondos\\alex.jpg"));
    /**
     * Creates new form cliente
     */
    public cliente(){
        initComponents();
        AWTUtilities.setWindowOpaque(this,false); //hacemos el frame transparente
        this.setLocationRelativeTo(null);  //centramos el frame
        try
        {
            BufferedImage bim = ImageIO.read(new File(System.getProperty("user.dir") + "\\src\\fondos\\f8.jpg")); //creo un bufferimage con una imagen para el fondo
            BufferedImage nbim = new BufferedImage (1001,1001, BufferedImage.TYPE_4BYTE_ABGR_PRE); //creo otro bufferimage y le doy medidas, x, y y le doy el efecto de color que quiero
            Graphics2D createGraphics = nbim.createGraphics(); // creo una grafica a partir de la imagen
            createGraphics.drawImage(bim, null, 0, 0); //la dibujo
            float alp[] = new float[]{1f,0.65f,1f,0.65f}; // creo un vector con los valores para crear el efecto de transparencia
            float def [] = new float[]{0,0,0,0}; 
            RescaleOp r = new RescaleOp(alp, def, null);
            BufferedImage filter = r.filter(nbim, null); //creo un bufferimage con mi filtro y le mando la imagen que cree antes
            img.setIcon(new ImageIcon(filter)); 
            img2.setIcon(new ImageIcon(filter));
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        Thread mihilo = new Thread(this);
        mihilo.start();
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rSFotoCircle1 = new rojerusan.RSFotoCircle();
        btnnahomi = new rojerusan.RSMaterialButtonRectangle();
        rSFotoCircle2 = new rojerusan.RSFotoCircle();
        btnalex = new rojerusan.RSMaterialButtonRectangle();
        rSFotoCircle3 = new rojerusan.RSFotoCircle();
        btnhector = new rojerusan.RSMaterialButtonRectangle();
        rSFotoCircle4 = new rojerusan.RSFotoCircle();
        btnmynor = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnenviar = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtchat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmensaje = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle4 = new rojerusan.RSMaterialButtonRectangle();
        btncerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnip = new rojerusan.RSMaterialButtonRectangle();
        fotonick = new rojerusan.RSFotoCircle();
        btnnick = new rojerusan.RSMaterialButtonRectangle();
        img2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("_______________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, 40));

        rSFotoCircle1.setColorBorde(new java.awt.Color(153, 0, 153));
        rSFotoCircle1.setColorButtonOptions(new java.awt.Color(153, 0, 153));
        rSFotoCircle1.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/fondos/nahomi.jpg"))); // NOI18N
        jPanel1.add(rSFotoCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 203, 60, 60));

        btnnahomi.setBackground(new java.awt.Color(255, 255, 255));
        btnnahomi.setForeground(new java.awt.Color(153, 0, 153));
        btnnahomi.setText("NAHOMI TORRES");
        btnnahomi.setEnabled(false);
        btnnahomi.setFocusPainted(false);
        btnnahomi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnahomiMouseClicked(evt);
            }
        });
        jPanel1.add(btnnahomi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 330, -1));

        rSFotoCircle2.setColorBorde(new java.awt.Color(255, 255, 255));
        rSFotoCircle2.setColorButtonOptions(new java.awt.Color(255, 255, 255));
        rSFotoCircle2.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/fondos/alex.jpg"))); // NOI18N
        jPanel1.add(rSFotoCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 45, 60, 60));

        btnalex.setBackground(new java.awt.Color(255, 255, 255));
        btnalex.setForeground(new java.awt.Color(153, 0, 153));
        btnalex.setText("ALEX DE LEÓN");
        btnalex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnalexMouseClicked(evt);
            }
        });
        btnalex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalexActionPerformed(evt);
            }
        });
        jPanel1.add(btnalex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 330, -1));

        rSFotoCircle3.setColorBorde(new java.awt.Color(153, 0, 153));
        rSFotoCircle3.setColorButtonOptions(new java.awt.Color(153, 0, 153));
        rSFotoCircle3.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/fondos/hector.jpg"))); // NOI18N
        jPanel1.add(rSFotoCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 283, 60, 60));

        btnhector.setBackground(new java.awt.Color(255, 255, 255));
        btnhector.setForeground(new java.awt.Color(153, 0, 153));
        btnhector.setText("Hector Tello");
        btnhector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhectorMouseClicked(evt);
            }
        });
        jPanel1.add(btnhector, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 330, -1));

        rSFotoCircle4.setColorBorde(new java.awt.Color(153, 0, 153));
        rSFotoCircle4.setColorButtonOptions(new java.awt.Color(153, 0, 153));
        rSFotoCircle4.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/fondos/mynor.jpg"))); // NOI18N
        jPanel1.add(rSFotoCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 363, 60, 60));

        btnmynor.setBackground(new java.awt.Color(255, 255, 255));
        btnmynor.setForeground(new java.awt.Color(153, 0, 153));
        btnmynor.setText("Mynor Alvarez");
        btnmynor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmynorMouseClicked(evt);
            }
        });
        jPanel1.add(btnmynor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 330, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTACTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 800));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/f8.jpg"))); // NOI18N
        img.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                imgMouseDragged(evt);
            }
        });
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgMousePressed(evt);
            }
        });
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 382, 802));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnenviar.setBackground(new java.awt.Color(153, 0, 153));
        btnenviar.setText("Enviar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });
        jPanel2.add(btnenviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, -1, -1));

        jScrollPane1.setBorder(null);

        txtchat.setColumns(20);
        txtchat.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtchat.setRows(5);
        txtchat.setBorder(null);
        jScrollPane1.setViewportView(txtchat);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 460, 360));

        jScrollPane2.setBorder(null);

        txtmensaje.setColumns(20);
        txtmensaje.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtmensaje.setRows(5);
        txtmensaje.setBorder(null);
        jScrollPane2.setViewportView(txtmensaje);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 460, 150));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CHAT");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WHATSPACK");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, 40));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle3.setText("rSMaterialButtonRectangle3");
        jPanel2.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 500, 400));

        rSMaterialButtonRectangle4.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle4.setText("rSMaterialButtonRectangle4");
        jPanel2.add(rSMaterialButtonRectangle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 500, 190));

        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_Cancel_35px_1.png"))); // NOI18N
        btncerrar.setBorderPainted(false);
        btncerrar.setContentAreaFilled(false);
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_Cancel_40px.png"))); // NOI18N
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarMouseClicked(evt);
            }
        });
        jPanel2.add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 40, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_Scroll_Down_35px.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_Scroll_Down_40px.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 10, 50, 40));

        btnip.setBackground(new java.awt.Color(255, 255, 255));
        btnip.setForeground(new java.awt.Color(153, 0, 153));
        jPanel2.add(btnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 210, 50));

        fotonick.setColorBorde(new java.awt.Color(255, 255, 255));
        fotonick.setColorButtonOptions(new java.awt.Color(255, 255, 255));
        fotonick.setImagenDefault(null);
        jPanel2.add(fotonick, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 40, 40));

        btnnick.setBackground(new java.awt.Color(255, 255, 255));
        btnnick.setForeground(new java.awt.Color(153, 0, 153));
        jPanel2.add(btnnick, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 50));

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/f8.jpg"))); // NOI18N
        img2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                img2MouseDragged(evt);
            }
        });
        img2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img2MousePressed(evt);
            }
        });
        jPanel2.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 802));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 0, 560, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btncerrarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         this.setExtendedState(ICONIFIED); //funcion para minimizar
    }//GEN-LAST:event_jButton1MouseClicked

    private void img2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img2MousePressed
         x = evt.getX();
          y = evt.getY();
    }//GEN-LAST:event_img2MousePressed

    private void imgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMousePressed
          x = evt.getX();
          y = evt.getY();
    }//GEN-LAST:event_imgMousePressed

    private void imgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_imgMouseDragged

    private void img2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_img2MouseDragged

    private void btnnahomiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnahomiMouseClicked
        btnnick.setText("NAHOMI TORRES");
        fotonick.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/fondos/nahomi.jpg")));
        btnip.setText("IP: 192.168.43.94");
    }//GEN-LAST:event_btnnahomiMouseClicked

    private void btnalexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnalexMouseClicked
        btnnick.setText("ALEX DE LEÓN");
        fotonick.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/fondos/alex.jpg")));
        btnip.setText("IP: 192.168.43.93");
    }//GEN-LAST:event_btnalexMouseClicked

    private void btnhectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhectorMouseClicked
        btnnick.setText("Héctor Tello");
        fotonick.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/fondos/hector.jpg")));
        btnip.setText("IP: 192.168.43.27");
    }//GEN-LAST:event_btnhectorMouseClicked

    private void btnmynorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmynorMouseClicked
        btnnick.setText("Mynor Álvarez");
        fotonick.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/fondos/mynor.jpg")));
        btnip.setText("IP: 192.168.43.242");
    }//GEN-LAST:event_btnmynorMouseClicked

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        try
        {
            Socket misocket = new Socket("192.168.43.94", 9999);
            paquete_de_envio datos = new paquete_de_envio();
            datos.setNick(btnalex.getText());
            datos.setIp(btnip.getText().substring(4));
            System.out.println(datos.getIp());
            datos.setMensaje(txtmensaje.getText());
            ObjectOutputStream flujo_salida = new ObjectOutputStream(misocket.getOutputStream());
            flujo_salida.writeObject(datos);
            misocket.close();
            txtchat.append("\n" + "yo: " + txtmensaje.getText());
            txtmensaje.setText("");
        } catch(IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnenviarActionPerformed

    private void btnalexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnalexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnalex;
    private javax.swing.JButton btncerrar;
    private rojerusan.RSMaterialButtonRectangle btnenviar;
    private rojerusan.RSMaterialButtonRectangle btnhector;
    private rojerusan.RSMaterialButtonRectangle btnip;
    private rojerusan.RSMaterialButtonRectangle btnmynor;
    private rojerusan.RSMaterialButtonRectangle btnnahomi;
    private rojerusan.RSMaterialButtonRectangle btnnick;
    private rojerusan.RSFotoCircle fotonick;
    private javax.swing.JLabel img;
    private javax.swing.JLabel img2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSFotoCircle rSFotoCircle1;
    private rojerusan.RSFotoCircle rSFotoCircle2;
    private rojerusan.RSFotoCircle rSFotoCircle3;
    private rojerusan.RSFotoCircle rSFotoCircle4;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle4;
    private javax.swing.JTextArea txtchat;
    private javax.swing.JTextArea txtmensaje;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
            ServerSocket socketservidor = new ServerSocket(9090);
            Socket cliente;
            paquete_de_envio paquete_recibido = new paquete_de_envio();
            while(true)
            {
                cliente = socketservidor.accept();
                ObjectInputStream flujo_entrada = new ObjectInputStream(cliente.getInputStream());
                paquete_recibido = (paquete_de_envio) flujo_entrada.readObject();
                txtchat.append("\n" + paquete_recibido.getNick() + ": "
                + paquete_recibido.getMensaje());
            }
        } catch (IOException | ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
    }
}
